spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/news?useSSL=false&characterEncoding=UTF-8

database:
  url: test

logging:
  level:
    org:
      hibernate:
        SQL: debug
